name: Builder
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0/30 * * * *"

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: test-ls
        run: ls

      - name: test-ls2
        run: ls ./research-group-static-web

      - name: Build the website with the latest contents
        uses: ./action-build

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}